# Site wide configuration

title:            Rintze Zelle
locale:           en_US
url:              http://rintze.zelle.me

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Rintze M. Zelle
  avatar: bio-photo-rmz.jpg
  bio: "Scientist in biotechnology, Citation Style Language-developer."
  email:
  disqus-shortname:
  twitter: rintzezelle
  facebook: #username
  google:
    plus: #username
    analytics: UA-48393242-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: rmzelle
  stackoverflow: 1712389/rintze-zelle
  linkedin: rintzezelle
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
